version: '2'

services:
  rc-4pcs:
    image: rc-4pcs:latest
    build:
      context: context
      dockerfile: ../Dockerfile
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../rc-4pcs:/catkin_ws/src/rc-4pcs
    command: sleep infinity
    restart: always
