version: '2.4'

services:
  app:
    image: richardcanik/point-cloud-registration
    runtime: nvidia
    build:
      context: context
      dockerfile: ../Dockerfile
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../point-cloud-registration:/catkin_ws/src/point-cloud-registration

      - ./context/upload:/upload             # TODO in future use docker volume
      - ./context/devel:/catkin_ws/devel     # TODO temporary mount to cache
      - /home/richard/Documents/clion:/clion # TODO just for development
    ports:
      - 9090:9090
    command: sleep infinity
    restart: always
