version: '2'

services:
  rc-4pcs:
    image: rc-4pcs:latest
    build:
      context: context
      dockerfile: ../Dockerfile
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../rc-4pcs:/catkin_ws/src/rc-4pcs
      - ./context/upload:/upload            # TODO in future use docker volume

      - ./context/devel:/catkin_ws/devel    # TODO temporary mount to cache build
    ports:
      - 9090:9090
    command: sleep infinity
    restart: always
